In [ ]:
#Name: Sajag Agrawal
#PRN: 25070123100
#experiment 11
#Aim: To create data sets and load data sets in pandas library

In [1]:
#dataset creation
import pandas as pd

data={
    "Roll_no.":[100,101,102,101,104],
    "Gender":["M","F","M","F","M"],
    "Department":["Entc","computer","mechanical","computer","computer"],
    "CGPA":[9.03,8.2,7.5,8.2,8.7]
}

df=pd.DataFrame(data)
print("the data set is:\n",df)
print()
#converting data into csv format

df.to_csv("students.csv",index=False) #index =false means that the indexing which is coming would not come here #if index= true than ak column aur banegajisme indexing bhi aayegi

#displays the shape of data set
print("the shape of data set is:",df.shape)
print()
#displying the size of dataset
print("the size of data set is:",df.size)
print()
#displayng informtion about dataset
print(df.info())
print()

#performing statistical analyis on numeric data
#this 25 percent50 percent are quartiles like q1 q2 q3 like q1 ho gaye 25 percent matlab last 25 percent bache than 50 percent ho gya 25 sai upar and 50 perent baccho sai neeche ya equal etc
display(df.describe())
print()
#tells no.of duplicated values
print("no. of duplicated values are:",df.duplicated().sum())
print()

the data set is:
    Roll_no. Gender  Department  CGPA
0       100      M        Entc  9.03
1       101      F    computer  8.20
2       102      M  mechanical  7.50
3       101      F    computer  8.20
4       104      M    computer  8.70

the shape of data set is: (5, 4)

the size of data set is: 20

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_no.    5 non-null      int64
 1   Gender      5 non-null      object
 2   Department  5 non-null      object
 3   CGPA        5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes
None

         Roll_no.      CGPA
count    5.000000  5.000000
mean   101.600000  8.326000
std      1.516575  0.580844
min    100.000000  7.500000
25%    101.000000  8.200000
50%    101.000000  8.200000
75%    102.000000  8.700000
max    104.000000  9.030000

no. of duplicated values are: 1

In [3]:
#uploading the dataset
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Cars93.csv")
display(df)
print()

# displaying no. of rows and columns
print("no. of rows and columns are:",df.shape)
print()

#displaying no. of elements in data set

print("no. of elements in data set are:",df.size)
print()

#display information about dataet

display(df.info())
print()

#applying statisical analysis

display(df.describe())
print()

#displays first 5 rows
display("first 5 rows are:",df.head())
print()

##displays last 5 rows
display("last 5 rows are:",df.tail())
print()

#print some sample rows
display("5 random rows re:",df.sample(5))
print()

#tells no. of null values in columns
display("no. of null values in each column are :",df.isnull().sum())
print()

#tells name of columns
print("name of columns are:",df.columns)
print()

#tells no.of duplicated rows
print("no. of duplicated values are:",df.duplicated().sum())
print()

#tells no.of unique elements
display("no. of unique elements are:\n",df.nunique())
print()

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0
...,...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

no. of rows and columns are: (93, 10)

no. of elements in data set are: 930

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

None

,Price,MPG.city,Horsepower,Passengers,Rear.seat.room,Luggage.room
count,93.000000,93.000000,93.000000,93.000000,91.000000,82.000000
mean,19.509677,22.365591,143.827957,5.086022,27.829670,13.890244
std,9.659430,5.619812,52.374410,1.038979,2.989072,2.997967
min,7.400000,15.000000,55.000000,2.000000,19.000000,6.000000
25%,12.200000,18.000000,103.000000,4.000000,26.000000,12.000000
50%,17.700000,21.000000,140.000000,5.000000,27.500000,14.000000
75%,23.300000,25.000000,170.000000,6.000000,30.000000,15.000000
max,61.900000,46.000000,300.000000,8.000000,36.000000,22.000000

'first 5 rows are:'

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
0,Acura,Integra,Small,15.9,25,NaN,140,5,26.5,11.0
1,Acura,Legend,Midsize,33.9,18,Driver & Passenger,200,5,30.0,15.0
2,Audi,90,Compact,29.1,20,Driver only,172,5,28.0,14.0
3,Audi,100,Midsize,37.7,19,Driver & Passenger,172,6,31.0,17.0
4,BMW,535i,Midsize,30.0,22,Driver only,208,4,27.0,13.0

'last 5 rows are:'

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
88,Volkswagen,Eurovan,Van,19.7,17,NaN,109,7,34.0,NaN
89,Volkswagen,Passat,Compact,20.0,21,NaN,134,5,31.5,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
91,Volvo,240,Compact,22.7,21,Driver only,114,5,29.5,14.0
92,Volvo,850,Midsize,26.7,20,Driver & Passenger,168,5,30.0,15.0

'5 random rows re:'

,Manufacturer,Model,Type,Price,MPG.city,AirBags,Horsepower,Passengers,Rear.seat.room,Luggage.room
72,Pontiac,LeMans,Small,9.0,31,NaN,74,4,25.5,17.0
81,Subaru,Legacy,Compact,19.5,23,Driver only,130,5,27.0,14.0
90,Volkswagen,Corrado,Sporty,23.3,18,NaN,178,4,26.0,15.0
53,Mazda,Protege,Small,11.6,28,NaN,103,5,26.5,13.0
78,Saturn,SL,Small,11.1,28,Driver only,85,5,26.5,12.0

'no. of null values in each column are :'

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

name of columns are: Index(['Manufacturer', 'Model', 'Type', 'Price', 'MPG.city', 'AirBags',
       'Horsepower', 'Passengers', 'Rear.seat.room', 'Luggage.room'],
      dtype='object')

no. of duplicated values are: 0

'no. of unique elements are:\n'

Manufacturer      32
Model             93
Type               6
Price             81
MPG.city          21
AirBags            2
Horsepower        57
Passengers         6
Rear.seat.room    24
Luggage.room      16
dtype: int64